gpp @a -c demoExt.cpp -o ..\demoExt.obj
gpp @a -c src\lib\An\AliasAnalysis.cpp -o ..\AliasAnalysis.obj
gpp @a -c src\lib\An\AliasAnalysisEvaluator.cpp -o ..\AliasAnalysisEvaluator.obj
gpp @a -c src\lib\An\AliasSetTracker.cpp -o ..\AliasSetTracker.obj
gpp @a -c src\lib\An\Analysis.cpp -o ..\Analysis.obj
gpp @a -c src\lib\An\AssumptionCache.cpp -o ..\AssumptionCache.obj
gpp @a -c src\lib\An\BasicAliasAnalysis.cpp -o ..\BasicAliasAnalysis.obj
gpp @a -c src\lib\An\BlockFrequencyInfo.cpp -o ..\BlockFrequencyInfo.obj
gpp @a -c src\lib\An\BlockFrequencyInfoImpl.cpp -o ..\BlockFrequencyInfoImpl.obj
gpp @a -c src\lib\An\BranchProbabilityInfo.cpp -o ..\BranchProbabilityInfo.obj
gpp @a -c src\lib\An\CallGraph.cpp -o ..\CallGraph.obj
gpp @a -c src\lib\An\CallGraphSCCPass.cpp -o ..\CallGraphSCCPass.obj
gpp @a -c src\lib\An\CallPrinter.cpp -o ..\CallPrinter.obj
gpp @a -c src\lib\An\CaptureTracking.cpp -o ..\CaptureTracking.obj
gpp @a -c src\lib\An\CFG.cpp -o ..\CFG.obj
gpp @a -c src\lib\An\CFGPrinter.cpp -o ..\CFGPrinter.obj
gpp @a -c src\lib\An\CFLAliasAnalysis.cpp -o ..\CFLAliasAnalysis.obj
gpp @a -c src\lib\An\CGSCCPassManager.cpp -o ..\CGSCCPassManager.obj
gpp @a -c src\lib\An\CodeMetrics.cpp -o ..\CodeMetrics.obj
gpp @a -c src\lib\An\ConstantFolding.cpp -o ..\ConstantFolding.obj
gpp @a -c src\lib\An\CostModel.cpp -o ..\CostModel.obj
gpp @a -c src\lib\An\Delinearization.cpp -o ..\Delinearization.obj
gpp @a -c src\lib\An\DemandedBits.cpp -o ..\DemandedBits.obj
gpp @a -c src\lib\An\DependenceAnalysis.cpp -o ..\DependenceAnalysis.obj
gpp @a -c src\lib\An\DivergenceAnalysis.cpp -o ..\DivergenceAnalysis.obj
gpp @a -c src\lib\An\DominanceFrontier.cpp -o ..\DominanceFrontier.obj
gpp @a -c src\lib\An\DomPrinter.cpp -o ..\DomPrinter.obj
gpp @a -c src\lib\An\EHPersonalities.cpp -o ..\EHPersonalities.obj
gpp @a -c src\lib\An\GlobalsModRef.cpp -o ..\GlobalsModRef.obj
gpp @a -c src\lib\An\InlineCost.cpp -o ..\InlineCost.obj
gpp @a -c src\lib\An\InstCount.cpp -o ..\InstCount.obj
gpp @a -c src\lib\An\InstructionSimplify.cpp -o ..\InstructionSimplify.obj
gpp @a -c src\lib\An\Interval.cpp -o ..\Interval.obj
gpp @a -c src\lib\An\IntervalPartition.cpp -o ..\IntervalPartition.obj
gpp @a -c src\lib\An\IteratedDominanceFrontier.cpp -o ..\IteratedDominanceFrontier.obj
gpp @a -c src\lib\An\IVUsers.cpp -o ..\IVUsers.obj
gpp @a -c src\lib\An\LazyCallGraph.cpp -o ..\LazyCallGraph.obj
gpp @a -c src\lib\An\LazyValueInfo.cpp -o ..\LazyValueInfo.obj
gpp @a -c src\lib\An\Lint.cpp -o ..\Lint.obj
gpp @a -c src\lib\An\Loads.cpp -o ..\Loads.obj
gpp @a -c src\lib\An\LoopAccessAnalysis.cpp -o ..\LoopAccessAnalysis.obj
gpp @a -c src\lib\An\LoopInfo.cpp -o ..\LoopInfo.obj
gpp @a -c src\lib\An\LoopPass.cpp -o ..\LoopPass.obj
gpp @a -c src\lib\An\MemDepPrinter.cpp -o ..\MemDepPrinter.obj
gpp @a -c src\lib\An\MemDerefPrinter.cpp -o ..\MemDerefPrinter.obj
gpp @a -c src\lib\An\MemoryBuiltins.cpp -o ..\MemoryBuiltins.obj
gpp @a -c src\lib\An\MemoryDependenceAnalysis.cpp -o ..\MemoryDependenceAnalysis.obj
gpp @a -c src\lib\An\MemoryLocation.cpp -o ..\MemoryLocation.obj
gpp @a -c src\lib\An\ModuleDebugInfoPrinter.cpp -o ..\ModuleDebugInfoPrinter.obj
gpp @a -c src\lib\An\ObjCARCAliasAnalysis.cpp -o ..\ObjCARCAliasAnalysis.obj
gpp @a -c src\lib\An\ObjCARCAnalysisUtils.cpp -o ..\ObjCARCAnalysisUtils.obj
gpp @a -c src\lib\An\ObjCARCInstKind.cpp -o ..\ObjCARCInstKind.obj
gpp @a -c src\lib\An\OrderedBasicBlock.cpp -o ..\OrderedBasicBlock.obj
gpp @a -c src\lib\An\PHITransAddr.cpp -o ..\PHITransAddr.obj
gpp @a -c src\lib\An\PostDominators.cpp -o ..\PostDominators.obj
gpp @a -c src\lib\An\PtrUseVisitor.cpp -o ..\PtrUseVisitor.obj
gpp @a -c src\lib\An\RegionInfo.cpp -o ..\RegionInfo.obj
gpp @a -c src\lib\An\RegionPass.cpp -o ..\RegionPass.obj
gpp @a -c src\lib\An\RegionPrinter.cpp -o ..\RegionPrinter.obj
gpp @a -c src\lib\An\ScalarEvolution.cpp -o ..\ScalarEvolution.obj
gpp @a -c src\lib\An\ScalarEvolutionAliasAnalysis.cpp -o ..\ScalarEvolutionAliasAnalysis.obj
gpp @a -c src\lib\An\ScalarEvolutionExpander.cpp -o ..\ScalarEvolutionExpander.obj
gpp @a -c src\lib\An\ScalarEvolutionNormalization.cpp -o ..\ScalarEvolutionNormalization.obj
gpp @a -c src\lib\An\ScopedNoAliasAA.cpp -o ..\ScopedNoAliasAA.obj
gpp @a -c src\lib\An\SparsePropagation.cpp -o ..\SparsePropagation.obj
gpp @a -c src\lib\An\TargetLibraryInfo.cpp -o ..\TargetLibraryInfo.obj
gpp @a -c src\lib\An\TargetTransformInfo.cpp -o ..\TargetTransformInfo.obj
gpp @a -c src\lib\An\Trace.cpp -o ..\Trace.obj
gpp @a -c src\lib\An\TypeBasedAliasAnalysis.cpp -o ..\TypeBasedAliasAnalysis.obj
gpp @a -c src\lib\An\ValueTracking.cpp -o ..\ValueTracking.obj
gpp @a -c src\lib\An\VectorUtils.cpp -o ..\VectorUtils.obj
gpp @a -c src\lib\AsmParser\LLLexer.cpp -o ..\LLLexer.obj
gpp @a -c src\lib\AsmParser\LLParser.cpp -o ..\LLParser.obj
gpp @a -c src\lib\AsmParser\Parser.cpp -o ..\Parser.obj
gpp @a -c src\lib\Bitcode\Reader\BitcodeReader.cpp -o ..\BitcodeReader.obj
gpp @a -c src\lib\Bitcode\Reader\BitReader.cpp -o ..\BitReader.obj
gpp @a -c src\lib\Bitcode\Reader\BitstreamReader.cpp -o ..\BitstreamReader.obj
gpp @a -c src\lib\Bitcode\Writer\BitcodeWriter.cpp -o ..\BitcodeWriter.obj
gpp @a -c src\lib\Bitcode\Writer\BitcodeWriterPass.cpp -o ..\BitcodeWriterPass.obj
gpp @a -c src\lib\Bitcode\Writer\BitWriter.cpp -o ..\BitWriter.obj
gpp @a -c src\lib\Bitcode\Writer\ValueEnumerator.cpp -o ..\ValueEnumerator.obj
gpp @a -c src\lib\CG\AggressiveAntiDepBreaker.cpp -o ..\AggressiveAntiDepBreaker.obj
gpp @a -c src\lib\CG\AllocationOrder.cpp -o ..\AllocationOrder.obj
gpp @a -c src\lib\CG\Analysis.cpp -o ..\Analysis_2.obj
gpp @a -c src\lib\CG\AsmPrinter\AddressPool.cpp -o ..\AddressPool.obj
gpp @a -c src\lib\CG\AsmPrinter\ARMException.cpp -o ..\ARMException.obj
gpp @a -c src\lib\CG\AsmPrinter\AsmPrinter.cpp -o ..\AsmPrinter.obj
gpp @a -c src\lib\CG\AsmPrinter\AsmPrinterDwarf.cpp -o ..\AsmPrinterDwarf.obj
gpp @a -c src\lib\CG\AsmPrinter\AsmPrinterInlineAsm.cpp -o ..\AsmPrinterInlineAsm.obj
gpp @a -c src\lib\CG\AsmPrinter\DbgValueHistoryCalculator.cpp -o ..\DbgValueHistoryCalculator.obj
gpp @a -c src\lib\CG\AsmPrinter\DebugLocStream.cpp -o ..\DebugLocStream.obj
gpp @a -c src\lib\CG\AsmPrinter\DIE.cpp -o ..\DIE.obj
gpp @a -c src\lib\CG\AsmPrinter\DIEHash.cpp -o ..\DIEHash.obj
gpp @a -c src\lib\CG\AsmPrinter\DwarfAccelTable.cpp -o ..\DwarfAccelTable.obj
gpp @a -c src\lib\CG\AsmPrinter\DwarfCFIException.cpp -o ..\DwarfCFIException.obj
gpp @a -c src\lib\CG\AsmPrinter\DwarfCompileUnit.cpp -o ..\DwarfCompileUnit.obj
gpp @a -c src\lib\CG\AsmPrinter\DwarfDebug.cpp -o ..\DwarfDebug.obj
gpp @a -c src\lib\CG\AsmPrinter\DwarfExpression.cpp -o ..\DwarfExpression.obj
gpp @a -c src\lib\CG\AsmPrinter\DwarfFile.cpp -o ..\DwarfFile.obj
gpp @a -c src\lib\CG\AsmPrinter\DwarfStringPool.cpp -o ..\DwarfStringPool.obj
gpp @a -c src\lib\CG\AsmPrinter\DwarfUnit.cpp -o ..\DwarfUnit.obj
gpp @a -c src\lib\CG\AsmPrinter\EHStreamer.cpp -o ..\EHStreamer.obj
gpp @a -c src\lib\CG\AsmPrinter\ErlangGCPrinter.cpp -o ..\ErlangGCPrinter.obj
gpp @a -c src\lib\CG\AsmPrinter\OcamlGCPrinter.cpp -o ..\OcamlGCPrinter.obj
gpp @a -c src\lib\CG\AsmPrinter\WinCodeViewLineTables.cpp -o ..\WinCodeViewLineTables.obj
gpp @a -c src\lib\CG\AsmPrinter\WinException.cpp -o ..\WinException.obj
gpp @a -c src\lib\CG\AtomicExpandPass.cpp -o ..\AtomicExpandPass.obj
gpp @a -c src\lib\CG\BasicTargetTransformInfo.cpp -o ..\BasicTargetTransformInfo.obj
gpp @a -c src\lib\CG\BranchFolding.cpp -o ..\BranchFolding.obj
gpp @a -c src\lib\CG\CalcSpillWeights.cpp -o ..\CalcSpillWeights.obj
gpp @a -c src\lib\CG\CallingConvLower.cpp -o ..\CallingConvLower.obj
gpp @a -c src\lib\CG\CodeGen.cpp -o ..\CodeGen.obj
gpp @a -c src\lib\CG\CodeGenPrepare.cpp -o ..\CodeGenPrepare.obj
gpp @a -c src\lib\CG\CoreCLRGC.cpp -o ..\CoreCLRGC.obj
gpp @a -c src\lib\CG\CriticalAntiDepBreaker.cpp -o ..\CriticalAntiDepBreaker.obj
gpp @a -c src\lib\CG\DeadMachineInstructionElim.cpp -o ..\DeadMachineInstructionElim.obj
gpp @a -c src\lib\CG\DFAPacketizer.cpp -o ..\DFAPacketizer.obj
gpp @a -c src\lib\CG\DwarfEHPrepare.cpp -o ..\DwarfEHPrepare.obj
gpp @a -c src\lib\CG\EarlyIfConversion.cpp -o ..\EarlyIfConversion.obj
gpp @a -c src\lib\CG\EdgeBundles.cpp -o ..\EdgeBundles.obj
gpp @a -c src\lib\CG\ErlangGC.cpp -o ..\ErlangGC.obj
gpp @a -c src\lib\CG\ExecutionDepsFix.cpp -o ..\ExecutionDepsFix.obj
gpp @a -c src\lib\CG\ExpandISelPseudos.cpp -o ..\ExpandISelPseudos.obj
gpp @a -c src\lib\CG\ExpandPostRAPseudos.cpp -o ..\ExpandPostRAPseudos.obj
gpp @a -c src\lib\CG\FaultMaps.cpp -o ..\FaultMaps.obj
gpp @a -c src\lib\CG\FuncletLayout.cpp -o ..\FuncletLayout.obj
gpp @a -c src\lib\CG\GCMetadata.cpp -o ..\GCMetadata.obj
gpp @a -c src\lib\CG\GCMetadataPrinter.cpp -o ..\GCMetadataPrinter.obj
gpp @a -c src\lib\CG\GCRootLowering.cpp -o ..\GCRootLowering.obj
gpp @a -c src\lib\CG\GCStrategy.cpp -o ..\GCStrategy.obj
gpp @a -c src\lib\CG\GlobalMerge.cpp -o ..\GlobalMerge.obj
gpp @a -c src\lib\CG\IfConversion.cpp -o ..\IfConversion.obj
gpp @a -c src\lib\CG\ImplicitNullChecks.cpp -o ..\ImplicitNullChecks.obj
gpp @a -c src\lib\CG\InlineSpiller.cpp -o ..\InlineSpiller.obj
gpp @a -c src\lib\CG\InterferenceCache.cpp -o ..\InterferenceCache.obj
gpp @a -c src\lib\CG\InterleavedAccessPass.cpp -o ..\InterleavedAccessPass.obj
gpp @a -c src\lib\CG\IntrinsicLowering.cpp -o ..\IntrinsicLowering.obj
gpp @a -c src\lib\CG\LatencyPriorityQueue.cpp -o ..\LatencyPriorityQueue.obj
gpp @a -c src\lib\CG\LexicalScopes.cpp -o ..\LexicalScopes.obj
gpp @a -c src\lib\CG\LiveDebugValues.cpp -o ..\LiveDebugValues.obj
gpp @a -c src\lib\CG\LiveDebugVariables.cpp -o ..\LiveDebugVariables.obj
gpp @a -c src\lib\CG\LiveInterval.cpp -o ..\LiveInterval.obj
gpp @a -c src\lib\CG\LiveIntervalAnalysis.cpp -o ..\LiveIntervalAnalysis.obj
gpp @a -c src\lib\CG\LiveIntervalUnion.cpp -o ..\LiveIntervalUnion.obj
gpp @a -c src\lib\CG\LivePhysRegs.cpp -o ..\LivePhysRegs.obj
gpp @a -c src\lib\CG\LiveRangeCalc.cpp -o ..\LiveRangeCalc.obj
gpp @a -c src\lib\CG\LiveRangeEdit.cpp -o ..\LiveRangeEdit.obj
gpp @a -c src\lib\CG\LiveRegMatrix.cpp -o ..\LiveRegMatrix.obj
gpp @a -c src\lib\CG\LiveStackAnalysis.cpp -o ..\LiveStackAnalysis.obj
gpp @a -c src\lib\CG\LiveVariables.cpp -o ..\LiveVariables.obj
gpp @a -c src\lib\CG\LLVMTargetMachine.cpp -o ..\LLVMTargetMachine.obj
gpp @a -c src\lib\CG\LocalStackSlotAllocation.cpp -o ..\LocalStackSlotAllocation.obj
gpp @a -c src\lib\CG\MachineBasicBlock.cpp -o ..\MachineBasicBlock.obj
gpp @a -c src\lib\CG\MachineBlockFrequencyInfo.cpp -o ..\MachineBlockFrequencyInfo.obj
gpp @a -c src\lib\CG\MachineBlockPlacement.cpp -o ..\MachineBlockPlacement.obj
gpp @a -c src\lib\CG\MachineBranchProbabilityInfo.cpp -o ..\MachineBranchProbabilityInfo.obj
gpp @a -c src\lib\CG\MachineCombiner.cpp -o ..\MachineCombiner.obj
gpp @a -c src\lib\CG\MachineCopyPropagation.cpp -o ..\MachineCopyPropagation.obj
gpp @a -c src\lib\CG\MachineCSE.cpp -o ..\MachineCSE.obj
gpp @a -c src\lib\CG\MachineDominanceFrontier.cpp -o ..\MachineDominanceFrontier.obj
gpp @a -c src\lib\CG\MachineDominators.cpp -o ..\MachineDominators.obj
gpp @a -c src\lib\CG\MachineFunction.cpp -o ..\MachineFunction.obj
gpp @a -c src\lib\CG\MachineFunctionAnalysis.cpp -o ..\MachineFunctionAnalysis.obj
gpp @a -c src\lib\CG\MachineFunctionPass.cpp -o ..\MachineFunctionPass.obj
gpp @a -c src\lib\CG\MachineFunctionPrinterPass.cpp -o ..\MachineFunctionPrinterPass.obj
gpp @a -c src\lib\CG\MachineInstr.cpp -o ..\MachineInstr.obj
gpp @a -c src\lib\CG\MachineInstrBundle.cpp -o ..\MachineInstrBundle.obj
gpp @a -c src\lib\CG\MachineLICM.cpp -o ..\MachineLICM.obj
gpp @a -c src\lib\CG\MachineLoopInfo.cpp -o ..\MachineLoopInfo.obj
gpp @a -c src\lib\CG\MachineModuleInfo.cpp -o ..\MachineModuleInfo.obj
gpp @a -c src\lib\CG\MachineModuleInfoImpls.cpp -o ..\MachineModuleInfoImpls.obj
gpp @a -c src\lib\CG\MachinePassRegistry.cpp -o ..\MachinePassRegistry.obj
gpp @a -c src\lib\CG\MachinePostDominators.cpp -o ..\MachinePostDominators.obj
gpp @a -c src\lib\CG\MachineRegionInfo.cpp -o ..\MachineRegionInfo.obj
gpp @a -c src\lib\CG\MachineRegisterInfo.cpp -o ..\MachineRegisterInfo.obj
gpp @a -c src\lib\CG\MachineScheduler.cpp -o ..\MachineScheduler.obj
gpp @a -c src\lib\CG\MachineSink.cpp -o ..\MachineSink.obj
gpp @a -c src\lib\CG\MachineSSAUpdater.cpp -o ..\MachineSSAUpdater.obj
gpp @a -c src\lib\CG\MachineTraceMetrics.cpp -o ..\MachineTraceMetrics.obj
gpp @a -c src\lib\CG\MachineVerifier.cpp -o ..\MachineVerifier.obj
gpp @a -c src\lib\CG\MIRPrinter.cpp -o ..\MIRPrinter.obj
gpp @a -c src\lib\CG\MIRPrintingPass.cpp -o ..\MIRPrintingPass.obj
gpp @a -c src\lib\CG\OcamlGC.cpp -o ..\OcamlGC.obj
gpp @a -c src\lib\CG\OptimizePHIs.cpp -o ..\OptimizePHIs.obj
gpp @a -c src\lib\CG\ParallelCG.cpp -o ..\ParallelCG.obj
gpp @a -c src\lib\CG\Passes.cpp -o ..\Passes.obj
gpp @a -c src\lib\CG\PeepholeOptimizer.cpp -o ..\PeepholeOptimizer.obj
gpp @a -c src\lib\CG\PHIElimination.cpp -o ..\PHIElimination.obj
gpp @a -c src\lib\CG\PHIEliminationUtils.cpp -o ..\PHIEliminationUtils.obj
gpp @a -c src\lib\CG\PostRASchedulerList.cpp -o ..\PostRASchedulerList.obj
gpp @a -c src\lib\CG\ProcessImplicitDefs.cpp -o ..\ProcessImplicitDefs.obj
gpp @a -c src\lib\CG\PrologEpilogInserter.cpp -o ..\PrologEpilogInserter.obj
gpp @a -c src\lib\CG\PseudoSourceValue.cpp -o ..\PseudoSourceValue.obj
gpp @a -c src\lib\CG\RegAllocBase.cpp -o ..\RegAllocBase.obj
gpp @a -c src\lib\CG\RegAllocBasic.cpp -o ..\RegAllocBasic.obj
gpp @a -c src\lib\CG\RegAllocFast.cpp -o ..\RegAllocFast.obj
gpp @a -c src\lib\CG\RegAllocGreedy.cpp -o ..\RegAllocGreedy.obj
gpp @a -c src\lib\CG\RegAllocPBQP.cpp -o ..\RegAllocPBQP.obj
gpp @a -c src\lib\CG\RegisterClassInfo.cpp -o ..\RegisterClassInfo.obj
gpp @a -c src\lib\CG\RegisterCoalescer.cpp -o ..\RegisterCoalescer.obj
gpp @a -c src\lib\CG\RegisterPressure.cpp -o ..\RegisterPressure.obj
gpp @a -c src\lib\CG\RegisterScavenging.cpp -o ..\RegisterScavenging.obj
gpp @a -c src\lib\CG\ScheduleDAG.cpp -o ..\ScheduleDAG.obj
gpp @a -c src\lib\CG\ScheduleDAGInstrs.cpp -o ..\ScheduleDAGInstrs.obj
gpp @a -c src\lib\CG\ScheduleDAGPrinter.cpp -o ..\ScheduleDAGPrinter.obj
gpp @a -c src\lib\CG\ScoreboardHazardRecognizer.cpp -o ..\ScoreboardHazardRecognizer.obj
gpp @a -c src\lib\CG\SelectionDAG\DAGCombiner.cpp -o ..\DAGCombiner.obj
gpp @a -c src\lib\CG\SelectionDAG\FastISel.cpp -o ..\FastISel.obj
gpp @a -c src\lib\CG\SelectionDAG\FunctionLoweringInfo.cpp -o ..\FunctionLoweringInfo.obj
gpp @a -c src\lib\CG\SelectionDAG\InstrEmitter.cpp -o ..\InstrEmitter.obj
gpp @a -c src\lib\CG\SelectionDAG\LegalizeDAG.cpp -o ..\LegalizeDAG.obj
gpp @a -c src\lib\CG\SelectionDAG\LegalizeFloatTypes.cpp -o ..\LegalizeFloatTypes.obj
gpp @a -c src\lib\CG\SelectionDAG\LegalizeIntegerTypes.cpp -o ..\LegalizeIntegerTypes.obj
gpp @a -c src\lib\CG\SelectionDAG\LegalizeTypes.cpp -o ..\LegalizeTypes.obj
gpp @a -c src\lib\CG\SelectionDAG\LegalizeTypesGeneric.cpp -o ..\LegalizeTypesGeneric.obj
gpp @a -c src\lib\CG\SelectionDAG\LegalizeVectorOps.cpp -o ..\LegalizeVectorOps.obj
gpp @a -c src\lib\CG\SelectionDAG\LegalizeVectorTypes.cpp -o ..\LegalizeVectorTypes.obj
gpp @a -c src\lib\CG\SelectionDAG\ResourcePriorityQueue.cpp -o ..\ResourcePriorityQueue.obj
gpp @a -c src\lib\CG\SelectionDAG\ScheduleDAGFast.cpp -o ..\ScheduleDAGFast.obj
gpp @a -c src\lib\CG\SelectionDAG\ScheduleDAGRRList.cpp -o ..\ScheduleDAGRRList.obj
gpp @a -c src\lib\CG\SelectionDAG\ScheduleDAGSDNodes.cpp -o ..\ScheduleDAGSDNodes.obj
gpp @a -c src\lib\CG\SelectionDAG\ScheduleDAGVLIW.cpp -o ..\ScheduleDAGVLIW.obj
gpp @a -c src\lib\CG\SelectionDAG\SelectionDAG.cpp -o ..\SelectionDAG.obj
gpp @a -c src\lib\CG\SelectionDAG\SelectionDAGBuilder.cpp -o ..\SelectionDAGBuilder.obj
gpp @a -c src\lib\CG\SelectionDAG\SelectionDAGDumper.cpp -o ..\SelectionDAGDumper.obj
gpp @a -c src\lib\CG\SelectionDAG\SelectionDAGISel.cpp -o ..\SelectionDAGISel.obj
gpp @a -c src\lib\CG\SelectionDAG\SelectionDAGPrinter.cpp -o ..\SelectionDAGPrinter.obj
gpp @a -c src\lib\CG\SelectionDAG\StatepointLowering.cpp -o ..\StatepointLowering.obj
gpp @a -c src\lib\CG\SelectionDAG\TargetLowering.cpp -o ..\TargetLowering.obj
gpp @a -c src\lib\CG\SelectionDAG\TargetSelectionDAGInfo.cpp -o ..\TargetSelectionDAGInfo.obj
gpp @a -c src\lib\CG\ShadowStackGC.cpp -o ..\ShadowStackGC.obj
gpp @a -c src\lib\CG\ShadowStackGCLowering.cpp -o ..\ShadowStackGCLowering.obj
gpp @a -c src\lib\CG\ShrinkWrap.cpp -o ..\ShrinkWrap.obj
gpp @a -c src\lib\CG\SjLjEHPrepare.cpp -o ..\SjLjEHPrepare.obj
gpp @a -c src\lib\CG\SlotIndexes.cpp -o ..\SlotIndexes.obj
gpp @a -c src\lib\CG\SpillPlacement.cpp -o ..\SpillPlacement.obj
gpp @a -c src\lib\CG\SplitKit.cpp -o ..\SplitKit.obj
gpp @a -c src\lib\CG\StackColoring.cpp -o ..\StackColoring.obj
gpp @a -c src\lib\CG\StackMapLivenessAnalysis.cpp -o ..\StackMapLivenessAnalysis.obj
gpp @a -c src\lib\CG\StackMaps.cpp -o ..\StackMaps.obj
gpp @a -c src\lib\CG\StackProtector.cpp -o ..\StackProtector.obj
gpp @a -c src\lib\CG\StackSlotColoring.cpp -o ..\StackSlotColoring.obj
gpp @a -c src\lib\CG\StatepointExampleGC.cpp -o ..\StatepointExampleGC.obj
gpp @a -c src\lib\CG\TailDuplication.cpp -o ..\TailDuplication.obj
gpp @a -c src\lib\CG\TargetFrameLoweringImpl.cpp -o ..\TargetFrameLoweringImpl.obj
gpp @a -c src\lib\CG\TargetInstrInfo.cpp -o ..\TargetInstrInfo.obj
gpp @a -c src\lib\CG\TargetLoweringBase.cpp -o ..\TargetLoweringBase.obj
gpp @a -c src\lib\CG\TargetLoweringObjectFileImpl.cpp -o ..\TargetLoweringObjectFileImpl.obj
gpp @a -c src\lib\CG\TargetOptionsImpl.cpp -o ..\TargetOptionsImpl.obj
gpp @a -c src\lib\CG\TargetRegisterInfo.cpp -o ..\TargetRegisterInfo.obj
gpp @a -c src\lib\CG\TargetSchedule.cpp -o ..\TargetSchedule.obj
gpp @a -c src\lib\CG\TwoAddressInstructionPass.cpp -o ..\TwoAddressInstructionPass.obj
gpp @a -c src\lib\CG\UnreachableBlockElim.cpp -o ..\UnreachableBlockElim.obj
gpp @a -c src\lib\CG\VirtRegMap.cpp -o ..\VirtRegMap.obj
gpp @a -c src\lib\CG\WinEHPrepare.cpp -o ..\WinEHPrepare.obj
gpp @a -c src\lib\EE\ExecutionEngine.cpp -o ..\ExecutionEngine.obj
gpp @a -c src\lib\EE\ExecutionEngineBindings.cpp -o ..\ExecutionEngineBindings.obj
gpp @a -c src\lib\EE\GDBRegistrationListener.cpp -o ..\GDBRegistrationListener.obj
gpp @a -c src\lib\EE\Interpreter\Execution.cpp -o ..\Execution.obj
gpp @a -c src\lib\EE\Interpreter\ExternalFunctions.cpp -o ..\ExternalFunctions.obj
gpp @a -c src\lib\EE\Interpreter\Interpreter.cpp -o ..\Interpreter.obj
gpp @a -c src\lib\EE\MCJIT\MCJIT.cpp -o ..\MCJIT.obj
gpp @a -c src\lib\EE\Orc\ExecutionUtils.cpp -o ..\ExecutionUtils.obj
gpp @a -c src\lib\EE\Orc\IndirectionUtils.cpp -o ..\IndirectionUtils.obj
gpp @a -c src\lib\EE\Orc\NullResolver.cpp -o ..\NullResolver.obj
gpp @a -c src\lib\EE\Orc\OrcArchitectureSupport.cpp -o ..\OrcArchitectureSupport.obj
gpp @a -c src\lib\EE\Orc\OrcCBindings.cpp -o ..\OrcCBindings.obj
gpp @a -c src\lib\EE\Orc\OrcCBindingsStack.cpp -o ..\OrcCBindingsStack.obj
gpp @a -c src\lib\EE\Orc\OrcError.cpp -o ..\OrcError.obj
gpp @a -c src\lib\EE\Orc\OrcMCJITReplacement.cpp -o ..\OrcMCJITReplacement.obj
gpp @a -c src\lib\EE\Orc\OrcRemoteTargetRPCAPI.cpp -o ..\OrcRemoteTargetRPCAPI.obj
gpp @a -c src\lib\EE\RuntimeDyld\RTDyldMemoryManager.cpp -o ..\RTDyldMemoryManager.obj
gpp @a -c src\lib\EE\RuntimeDyld\RuntimeDyld.cpp -o ..\RuntimeDyld.obj
gpp @a -c src\lib\EE\RuntimeDyld\RuntimeDyldChecker.cpp -o ..\RuntimeDyldChecker.obj
gpp @a -c src\lib\EE\RuntimeDyld\RuntimeDyldCOFF.cpp -o ..\RuntimeDyldCOFF.obj
gpp @a -c src\lib\EE\RuntimeDyld\RuntimeDyldELF.cpp -o ..\RuntimeDyldELF.obj
gpp @a -c src\lib\EE\RuntimeDyld\RuntimeDyldMachO.cpp -o ..\RuntimeDyldMachO.obj
gpp @a -c src\lib\EE\SectionMemoryManager.cpp -o ..\SectionMemoryManager.obj
gpp @a -c src\lib\EE\TargetSelect.cpp -o ..\TargetSelect.obj
gpp @a -c src\lib\IR\AsmWriter.cpp -o ..\AsmWriter.obj
gpp @a -c src\lib\IR\Attributes.cpp -o ..\Attributes.obj
gpp @a -c src\lib\IR\AutoUpgrade.cpp -o ..\AutoUpgrade.obj
gpp @a -c src\lib\IR\BasicBlock.cpp -o ..\BasicBlock.obj
gpp @a -c src\lib\IR\Comdat.cpp -o ..\Comdat.obj
gpp @a -c src\lib\IR\ConstantFold.cpp -o ..\ConstantFold.obj
gpp @a -c src\lib\IR\ConstantRange.cpp -o ..\ConstantRange.obj
gpp @a -c src\lib\IR\Constants.cpp -o ..\Constants.obj
gpp @a -c src\lib\IR\Core.cpp -o ..\Core.obj
gpp @a -c src\lib\IR\DataLayout.cpp -o ..\DataLayout.obj
gpp @a -c src\lib\IR\DebugInfo.cpp -o ..\DebugInfo.obj
gpp @a -c src\lib\IR\DebugInfoMetadata.cpp -o ..\DebugInfoMetadata.obj
gpp @a -c src\lib\IR\DebugLoc.cpp -o ..\DebugLoc.obj
gpp @a -c src\lib\IR\DiagnosticInfo.cpp -o ..\DiagnosticInfo.obj
gpp @a -c src\lib\IR\DiagnosticPrinter.cpp -o ..\DiagnosticPrinter.obj
gpp @a -c src\lib\IR\DIBuilder.cpp -o ..\DIBuilder.obj
gpp @a -c src\lib\IR\Dominators.cpp -o ..\Dominators.obj
gpp @a -c src\lib\IR\Function.cpp -o ..\Function.obj
gpp @a -c src\lib\IR\FunctionInfo.cpp -o ..\FunctionInfo.obj
gpp @a -c src\lib\IR\GCOV.cpp -o ..\GCOV.obj
gpp @a -c src\lib\IR\Globals.cpp -o ..\Globals.obj
gpp @a -c src\lib\IR\GVMaterializer.cpp -o ..\GVMaterializer.obj
gpp @a -c src\lib\IR\InlineAsm.cpp -o ..\InlineAsm.obj
gpp @a -c src\lib\IR\Instruction.cpp -o ..\Instruction.obj
gpp @a -c src\lib\IR\Instructions.cpp -o ..\Instructions.obj
gpp @a -c src\lib\IR\IntrinsicInst.cpp -o ..\IntrinsicInst.obj
gpp @a -c src\lib\IR\IRBuilder.cpp -o ..\IRBuilder.obj
gpp @a -c src\lib\IR\IRPrintingPasses.cpp -o ..\IRPrintingPasses.obj
gpp @a -c src\lib\IR\LegacyPassManager.cpp -o ..\LegacyPassManager.obj
gpp @a -c src\lib\IR\LLVMContext.cpp -o ..\LLVMContext.obj
gpp @a -c src\lib\IR\LLVMContextImpl.cpp -o ..\LLVMContextImpl.obj
gpp @a -c src\lib\IR\Mangler.cpp -o ..\Mangler.obj
gpp @a -c src\lib\IR\MDBuilder.cpp -o ..\MDBuilder.obj
gpp @a -c src\lib\IR\Metadata.cpp -o ..\Metadata.obj
gpp @a -c src\lib\IR\Module.cpp -o ..\Module.obj
gpp @a -c src\lib\IR\Operator.cpp -o ..\Operator.obj
gpp @a -c src\lib\IR\Pass.cpp -o ..\Pass.obj
gpp @a -c src\lib\IR\PassManager.cpp -o ..\PassManager.obj
gpp @a -c src\lib\IR\PassRegistry.cpp -o ..\PassRegistry.obj
gpp @a -c src\lib\IR\Statepoint.cpp -o ..\Statepoint.obj
gpp @a -c src\lib\IR\Type.cpp -o ..\Type.obj
gpp @a -c src\lib\IR\TypeFinder.cpp -o ..\TypeFinder.obj
gpp @a -c src\lib\IR\Use.cpp -o ..\Use.obj
gpp @a -c src\lib\IR\User.cpp -o ..\User.obj
gpp @a -c src\lib\IR\Value.cpp -o ..\Value.obj
gpp @a -c src\lib\IR\ValueSymbolTable.cpp -o ..\ValueSymbolTable.obj
gpp @a -c src\lib\IR\ValueTypes.cpp -o ..\ValueTypes.obj
gpp @a -c src\lib\IR\Verifier.cpp -o ..\Verifier.obj
gpp @a -c src\lib\IRReader\IRReader.cpp -o ..\IRReader.obj
gpp @a -c src\lib\Linker\IRMover.cpp -o ..\IRMover.obj
gpp @a -c src\lib\Linker\LinkModules.cpp -o ..\LinkModules.obj
gpp @a -c src\lib\MC\ConstantPools.cpp -o ..\ConstantPools.obj
gpp @a -c src\lib\MC\ELFObjectWriter.cpp -o ..\ELFObjectWriter.obj
gpp @a -c src\lib\MC\MachObjectWriter.cpp -o ..\MachObjectWriter.obj
gpp @a -c src\lib\MC\MCAsmBackend.cpp -o ..\MCAsmBackend.obj
gpp @a -c src\lib\MC\MCAsmInfo.cpp -o ..\MCAsmInfo.obj
gpp @a -c src\lib\MC\MCAsmInfoCOFF.cpp -o ..\MCAsmInfoCOFF.obj
gpp @a -c src\lib\MC\MCAsmInfoDarwin.cpp -o ..\MCAsmInfoDarwin.obj
gpp @a -c src\lib\MC\MCAsmInfoELF.cpp -o ..\MCAsmInfoELF.obj
gpp @a -c src\lib\MC\MCAsmStreamer.cpp -o ..\MCAsmStreamer.obj
gpp @a -c src\lib\MC\MCAssembler.cpp -o ..\MCAssembler.obj
gpp @a -c src\lib\MC\MCCodeEmitter.cpp -o ..\MCCodeEmitter.obj
gpp @a -c src\lib\MC\MCCodeGenInfo.cpp -o ..\MCCodeGenInfo.obj
gpp @a -c src\lib\MC\MCContext.cpp -o ..\MCContext.obj
gpp @a -c src\lib\MC\MCDisassembler\Disassembler.cpp -o ..\Disassembler.obj
gpp @a -c src\lib\MC\MCDisassembler\MCDisassembler.cpp -o ..\MCDisassembler.obj
gpp @a -c src\lib\MC\MCDisassembler\MCExternalSymbolizer.cpp -o ..\MCExternalSymbolizer.obj
gpp @a -c src\lib\MC\MCDisassembler\MCRelocationInfo.cpp -o ..\MCRelocationInfo.obj
gpp @a -c src\lib\MC\MCDwarf.cpp -o ..\MCDwarf.obj
gpp @a -c src\lib\MC\MCELFObjectTargetWriter.cpp -o ..\MCELFObjectTargetWriter.obj
gpp @a -c src\lib\MC\MCELFStreamer.cpp -o ..\MCELFStreamer.obj
gpp @a -c src\lib\MC\MCExpr.cpp -o ..\MCExpr.obj
gpp @a -c src\lib\MC\MCFragment.cpp -o ..\MCFragment.obj
gpp @a -c src\lib\MC\MCInst.cpp -o ..\MCInst.obj
gpp @a -c src\lib\MC\MCInstPrinter.cpp -o ..\MCInstPrinter.obj
gpp @a -c src\lib\MC\MCInstrAnalysis.cpp -o ..\MCInstrAnalysis.obj
gpp @a -c src\lib\MC\MCInstrDesc.cpp -o ..\MCInstrDesc.obj
gpp @a -c src\lib\MC\MCLabel.cpp -o ..\MCLabel.obj
gpp @a -c src\lib\MC\MCLinkerOptimizationHint.cpp -o ..\MCLinkerOptimizationHint.obj
gpp @a -c src\lib\MC\MCMachObjectTargetWriter.cpp -o ..\MCMachObjectTargetWriter.obj
gpp @a -c src\lib\MC\MCMachOStreamer.cpp -o ..\MCMachOStreamer.obj
gpp @a -c src\lib\MC\MCNullStreamer.cpp -o ..\MCNullStreamer.obj
gpp @a -c src\lib\MC\MCObjectFileInfo.cpp -o ..\MCObjectFileInfo.obj
gpp @a -c src\lib\MC\MCObjectStreamer.cpp -o ..\MCObjectStreamer.obj
gpp @a -c src\lib\MC\MCObjectWriter.cpp -o ..\MCObjectWriter.obj
gpp @a -c src\lib\MC\MCParser\AsmLexer.cpp -o ..\AsmLexer.obj
gpp @a -c src\lib\MC\MCParser\AsmParser.cpp -o ..\AsmParser.obj
gpp @a -c src\lib\MC\MCParser\COFFAsmParser.cpp -o ..\COFFAsmParser.obj
gpp @a -c src\lib\MC\MCParser\DarwinAsmParser.cpp -o ..\DarwinAsmParser.obj
gpp @a -c src\lib\MC\MCParser\ELFAsmParser.cpp -o ..\ELFAsmParser.obj
gpp @a -c src\lib\MC\MCParser\MCAsmLexer.cpp -o ..\MCAsmLexer.obj
gpp @a -c src\lib\MC\MCParser\MCAsmParser.cpp -o ..\MCAsmParser.obj
gpp @a -c src\lib\MC\MCParser\MCAsmParserExtension.cpp -o ..\MCAsmParserExtension.obj
gpp @a -c src\lib\MC\MCParser\MCTargetAsmParser.cpp -o ..\MCTargetAsmParser.obj
gpp @a -c src\lib\MC\MCRegisterInfo.cpp -o ..\MCRegisterInfo.obj
gpp @a -c src\lib\MC\MCSchedule.cpp -o ..\MCSchedule.obj
gpp @a -c src\lib\MC\MCSection.cpp -o ..\MCSection.obj
gpp @a -c src\lib\MC\MCSectionCOFF.cpp -o ..\MCSectionCOFF.obj
gpp @a -c src\lib\MC\MCSectionELF.cpp -o ..\MCSectionELF.obj
gpp @a -c src\lib\MC\MCSectionMachO.cpp -o ..\MCSectionMachO.obj
gpp @a -c src\lib\MC\MCStreamer.cpp -o ..\MCStreamer.obj
gpp @a -c src\lib\MC\MCSubtargetInfo.cpp -o ..\MCSubtargetInfo.obj
gpp @a -c src\lib\MC\MCSymbol.cpp -o ..\MCSymbol.obj
gpp @a -c src\lib\MC\MCSymbolELF.cpp -o ..\MCSymbolELF.obj
gpp @a -c src\lib\MC\MCSymbolizer.cpp -o ..\MCSymbolizer.obj
gpp @a -c src\lib\MC\MCTargetOptions.cpp -o ..\MCTargetOptions.obj
gpp @a -c src\lib\MC\MCValue.cpp -o ..\MCValue.obj
gpp @a -c src\lib\MC\MCWin64EH.cpp -o ..\MCWin64EH.obj
gpp @a -c src\lib\MC\MCWinEH.cpp -o ..\MCWinEH.obj
gpp @a -c src\lib\MC\StringTableBuilder.cpp -o ..\StringTableBuilder.obj
gpp @a -c src\lib\MC\SubtargetFeature.cpp -o ..\SubtargetFeature.obj
gpp @a -c src\lib\MC\WinCOFFObjectWriter.cpp -o ..\WinCOFFObjectWriter.obj
gpp @a -c src\lib\MC\WinCOFFStreamer.cpp -o ..\WinCOFFStreamer.obj
gpp @a -c src\lib\MC\YAML.cpp -o ..\YAML.obj
gpp @a -c src\lib\Object\Archive.cpp -o ..\Archive.obj
gpp @a -c src\lib\Object\ArchiveWriter.cpp -o ..\ArchiveWriter.obj
gpp @a -c src\lib\Object\Binary.cpp -o ..\Binary.obj
gpp @a -c src\lib\Object\COFFObjectFile.cpp -o ..\COFFObjectFile.obj
gpp @a -c src\lib\Object\ELF.cpp -o ..\ELF.obj
gpp @a -c src\lib\Object\ELFObjectFile.cpp -o ..\ELFObjectFile.obj
gpp @a -c src\lib\Object\ELFYAML.cpp -o ..\ELFYAML.obj
gpp @a -c src\lib\Object\Error.cpp -o ..\Error.obj
gpp @a -c src\lib\Object\FunctionIndexObjectFile.cpp -o ..\FunctionIndexObjectFile.obj
gpp @a -c src\lib\Object\IRObjectFile.cpp -o ..\IRObjectFile.obj
gpp @a -c src\lib\Object\MachOObjectFile.cpp -o ..\MachOObjectFile.obj
gpp @a -c src\lib\Object\MachOUniversal.cpp -o ..\MachOUniversal.obj
gpp @a -c src\lib\Object\Object.cpp -o ..\Object.obj
gpp @a -c src\lib\Object\ObjectFile.cpp -o ..\ObjectFile.obj
gpp @a -c src\lib\Object\RecordStreamer.cpp -o ..\RecordStreamer.obj
gpp @a -c src\lib\Object\SymbolicFile.cpp -o ..\SymbolicFile.obj
gpp @a -c src\lib\Object\SymbolSize.cpp -o ..\SymbolSize.obj
gpp @a -c src\lib\Option\Arg.cpp -o ..\Arg.obj
gpp @a -c src\lib\Option\ArgList.cpp -o ..\ArgList.obj
gpp @a -c src\lib\Option\Option.cpp -o ..\Option.obj
gpp @a -c src\lib\Option\OptTable.cpp -o ..\OptTable.obj
gpp @a -c src\lib\Passes\PassBuilder.cpp -o ..\PassBuilder.obj
gpp @a -c src\lib\ProfileData\SampleProf.cpp -o ..\SampleProf.obj
gpp @a -c src\lib\ProfileData\SampleProfReader.cpp -o ..\SampleProfReader.obj
gpp @a -c src\lib\ProfileData\SampleProfWriter.cpp -o ..\SampleProfWriter.obj
gpp @a -c src\lib\Support\Allocator.cpp -o ..\Allocator.obj
gpp @a -c src\lib\Support\APFloat.cpp -o ..\APFloat.obj
gpp @a -c src\lib\Support\APInt.cpp -o ..\APInt.obj
gpp @a -c src\lib\Support\APSInt.cpp -o ..\APSInt.obj
gpp @a -c src\lib\Support\ARMBuildAttrs.cpp -o ..\ARMBuildAttrs.obj
gpp @a -c src\lib\Support\ARMWinEH.cpp -o ..\ARMWinEH.obj
gpp @a -c src\lib\Support\Atomic.cpp -o ..\Atomic.obj
gpp @a -c src\lib\Support\BlockFrequency.cpp -o ..\BlockFrequency.obj
gpp @a -c src\lib\Support\BranchProbability.cpp -o ..\BranchProbability.obj
gpp @a -c src\lib\Support\circular_raw_ostream.cpp -o ..\circular_raw_ostream.obj
gpp @a -c src\lib\Support\CommandLine.cpp -o ..\CommandLine.obj
gpp @a -c src\lib\Support\Compression.cpp -o ..\Compression.obj
gpp @a -c src\lib\Support\ConvertUTF.c -o ..\ConvertUTF.obj
gpp @a -c src\lib\Support\ConvertUTFWrapper.cpp -o ..\ConvertUTFWrapper.obj
gpp @a -c src\lib\Support\DAGDeltaAlgorithm.cpp -o ..\DAGDeltaAlgorithm.obj
gpp @a -c src\lib\Support\DataExtractor.cpp -o ..\DataExtractor.obj
gpp @a -c src\lib\Support\DataStream.cpp -o ..\DataStream.obj
gpp @a -c src\lib\Support\Debug.cpp -o ..\Debug.obj
gpp @a -c src\lib\Support\DeltaAlgorithm.cpp -o ..\DeltaAlgorithm.obj
gpp @a -c src\lib\Support\Dwarf.cpp -o ..\Dwarf.obj
gpp @a -c src\lib\Support\DynamicLibrary.cpp -o ..\DynamicLibrary.obj
gpp @a -c src\lib\Support\Errno.cpp -o ..\Errno.obj
gpp @a -c src\lib\Support\ErrorHandling.cpp -o ..\ErrorHandling.obj
gpp @a -c src\lib\Support\FileOutputBuffer.cpp -o ..\FileOutputBuffer.obj
gpp @a -c src\lib\Support\FileUtilities.cpp -o ..\FileUtilities.obj
gpp @a -c src\lib\Support\FoldingSet.cpp -o ..\FoldingSet.obj
gpp @a -c src\lib\Support\FormattedStream.cpp -o ..\FormattedStream.obj
gpp @a -c src\lib\Support\GraphWriter.cpp -o ..\GraphWriter.obj
gpp @a -c src\lib\Support\Hashing.cpp -o ..\Hashing.obj
gpp @a -c src\lib\Support\Host.cpp -o ..\Host.obj
gpp @a -c src\lib\Support\IntEqClasses.cpp -o ..\IntEqClasses.obj
gpp @a -c src\lib\Support\IntervalMap.cpp -o ..\IntervalMap.obj
gpp @a -c src\lib\Support\IntrusiveRefCntPtr.cpp -o ..\IntrusiveRefCntPtr.obj
gpp @a -c src\lib\Support\JamCRC.cpp -o ..\JamCRC.obj
gpp @a -c src\lib\Support\LEB128.cpp -o ..\LEB128.obj
gpp @a -c src\lib\Support\LineIterator.cpp -o ..\LineIterator.obj
gpp @a -c src\lib\Support\Locale.cpp -o ..\Locale.obj
gpp @a -c src\lib\Support\LockFileManager.cpp -o ..\LockFileManager.obj
gpp @a -c src\lib\Support\ManagedStatic.cpp -o ..\ManagedStatic.obj
gpp @a -c src\lib\Support\MathExtras.cpp -o ..\MathExtras.obj
gpp @a -c src\lib\Support\MD5.cpp -o ..\MD5.obj
gpp @a -c src\lib\Support\Memory.cpp -o ..\Memory.obj
gpp @a -c src\lib\Support\MemoryBuffer.cpp -o ..\MemoryBuffer.obj
gpp @a -c src\lib\Support\MemoryObject.cpp -o ..\MemoryObject.obj
gpp @a -c src\lib\Support\Mutex.cpp -o ..\Mutex.obj
gpp @a -c src\lib\Support\Options.cpp -o ..\Options.obj
gpp @a -c src\lib\Support\Path.cpp -o ..\Path.obj
gpp @a -c src\lib\Support\PluginLoader.cpp -o ..\PluginLoader.obj
gpp @a -c src\lib\Support\PrettyStackTrace.cpp -o ..\PrettyStackTrace.obj
gpp @a -c src\lib\Support\Process.cpp -o ..\Process.obj
gpp @a -c src\lib\Support\Program.cpp -o ..\Program.obj
gpp @a -c src\lib\Support\RandomNumberGenerator.cpp -o ..\RandomNumberGenerator.obj
gpp @a -c src\lib\Support\raw_os_ostream.cpp -o ..\raw_os_ostream.obj
gpp @a -c src\lib\Support\raw_ostream.cpp -o ..\raw_ostream.obj
gpp @a -c src\lib\Support\regcomp.c -o ..\regcomp.obj
gpp @a -c src\lib\Support\regerror.c -o ..\regerror.obj
gpp @a -c src\lib\Support\Regex.cpp -o ..\Regex.obj
gpp @a -c src\lib\Support\regexec.c -o ..\regexec.obj
gpp @a -c src\lib\Support\regfree.c -o ..\regfree.obj
gpp @a -c src\lib\Support\regstrlcpy.c -o ..\regstrlcpy.obj
gpp @a -c src\lib\Support\RWMutex.cpp -o ..\RWMutex.obj
gpp @a -c src\lib\Support\ScaledNumber.cpp -o ..\ScaledNumber.obj
gpp @a -c src\lib\Support\SearchForAddressOfSpecialSymbol.cpp -o ..\SearchForAddressOfSpecialSymbol.obj
gpp @a -c src\lib\Support\Signals.cpp -o ..\Signals.obj
gpp @a -c src\lib\Support\SmallPtrSet.cpp -o ..\SmallPtrSet.obj
gpp @a -c src\lib\Support\SmallVector.cpp -o ..\SmallVector.obj
gpp @a -c src\lib\Support\SourceMgr.cpp -o ..\SourceMgr.obj
gpp @a -c src\lib\Support\SpecialCaseList.cpp -o ..\SpecialCaseList.obj
gpp @a -c src\lib\Support\Statistic.cpp -o ..\Statistic.obj
gpp @a -c src\lib\Support\StreamingMemoryObject.cpp -o ..\StreamingMemoryObject.obj
gpp @a -c src\lib\Support\StringExtras.cpp -o ..\StringExtras.obj
gpp @a -c src\lib\Support\StringMap.cpp -o ..\StringMap.obj
gpp @a -c src\lib\Support\StringPool.cpp -o ..\StringPool.obj
gpp @a -c src\lib\Support\StringRef.cpp -o ..\StringRef.obj
gpp @a -c src\lib\Support\StringSaver.cpp -o ..\StringSaver.obj
gpp @a -c src\lib\Support\SystemUtils.cpp -o ..\SystemUtils.obj
gpp @a -c src\lib\Support\TargetParser.cpp -o ..\TargetParser.obj
gpp @a -c src\lib\Support\TargetRegistry.cpp -o ..\TargetRegistry.obj
gpp @a -c src\lib\Support\Threading.cpp -o ..\Threading.obj
gpp @a -c src\lib\Support\ThreadLocal.cpp -o ..\ThreadLocal.obj
gpp @a -c src\lib\Support\Timer.cpp -o ..\Timer.obj
gpp @a -c src\lib\Support\TimeValue.cpp -o ..\TimeValue.obj
gpp @a -c src\lib\Support\ToolOutputFile.cpp -o ..\ToolOutputFile.obj
gpp @a -c src\lib\Support\Triple.cpp -o ..\Triple.obj
gpp @a -c src\lib\Support\Twine.cpp -o ..\Twine.obj
gpp @a -c src\lib\Support\Unicode.cpp -o ..\Unicode.obj
gpp @a -c src\lib\Support\Valgrind.cpp -o ..\Valgrind.obj
gpp @a -c src\lib\Support\Watchdog.cpp -o ..\Watchdog.obj
gpp @a -c src\lib\Support\YAMLParser.cpp -o ..\YAMLParser.obj
gpp @a -c src\lib\Support\YAMLTraits.cpp -o ..\YAMLTraits.obj
gpp @a -c src\lib\Tf\IC\InstCombineAddSub.cpp -o ..\InstCombineAddSub.obj
gpp @a -c src\lib\Tf\IC\InstCombineAndOrXor.cpp -o ..\InstCombineAndOrXor.obj
gpp @a -c src\lib\Tf\IC\InstCombineCalls.cpp -o ..\InstCombineCalls.obj
gpp @a -c src\lib\Tf\IC\InstCombineCasts.cpp -o ..\InstCombineCasts.obj
gpp @a -c src\lib\Tf\IC\InstCombineCompares.cpp -o ..\InstCombineCompares.obj
gpp @a -c src\lib\Tf\IC\InstCombineLoadStoreAlloca.cpp -o ..\InstCombineLoadStoreAlloca.obj
gpp @a -c src\lib\Tf\IC\InstCombineMulDivRem.cpp -o ..\InstCombineMulDivRem.obj
gpp @a -c src\lib\Tf\IC\InstCombinePHI.cpp -o ..\InstCombinePHI.obj
gpp @a -c src\lib\Tf\IC\InstCombineSelect.cpp -o ..\InstCombineSelect.obj
gpp @a -c src\lib\Tf\IC\InstCombineShifts.cpp -o ..\InstCombineShifts.obj
gpp @a -c src\lib\Tf\IC\InstCombineSimplifyDemanded.cpp -o ..\InstCombineSimplifyDemanded.obj
gpp @a -c src\lib\Tf\IC\InstCombineVectorOps.cpp -o ..\InstCombineVectorOps.obj
gpp @a -c src\lib\Tf\IC\InstructionCombining.cpp -o ..\InstructionCombining.obj
gpp @a -c src\lib\Tf\Ins\AddressSanitizer.cpp -o ..\AddressSanitizer.obj
gpp @a -c src\lib\Tf\Ins\BoundsChecking.cpp -o ..\BoundsChecking.obj
gpp @a -c src\lib\Tf\Ins\DataFlowSanitizer.cpp -o ..\DataFlowSanitizer.obj
gpp @a -c src\lib\Tf\Ins\GCOVProfiling.cpp -o ..\GCOVProfiling.obj
gpp @a -c src\lib\Tf\Ins\InstrProfiling.cpp -o ..\InstrProfiling.obj
gpp @a -c src\lib\Tf\Ins\MemorySanitizer.cpp -o ..\MemorySanitizer.obj
gpp @a -c src\lib\Tf\Ins\SafeStack.cpp -o ..\SafeStack.obj
gpp @a -c src\lib\Tf\Ins\ThreadSanitizer.cpp -o ..\ThreadSanitizer.obj
gpp @a -c src\lib\Tf\IPO\ArgumentPromotion.cpp -o ..\ArgumentPromotion.obj
gpp @a -c src\lib\Tf\IPO\BarrierNoopPass.cpp -o ..\BarrierNoopPass.obj
gpp @a -c src\lib\Tf\IPO\ConstantMerge.cpp -o ..\ConstantMerge.obj
gpp @a -c src\lib\Tf\IPO\CrossDSOCFI.cpp -o ..\CrossDSOCFI.obj
gpp @a -c src\lib\Tf\IPO\DeadArgumentElimination.cpp -o ..\DeadArgumentElimination.obj
gpp @a -c src\lib\Tf\IPO\ElimAvailExtern.cpp -o ..\ElimAvailExtern.obj
gpp @a -c src\lib\Tf\IPO\ExtractGV.cpp -o ..\ExtractGV.obj
gpp @a -c src\lib\Tf\IPO\ForceFunctionAttrs.cpp -o ..\ForceFunctionAttrs.obj
gpp @a -c src\lib\Tf\IPO\FunctionAttrs.cpp -o ..\FunctionAttrs.obj
gpp @a -c src\lib\Tf\IPO\FunctionImport.cpp -o ..\FunctionImport.obj
gpp @a -c src\lib\Tf\IPO\GlobalDCE.cpp -o ..\GlobalDCE.obj
gpp @a -c src\lib\Tf\IPO\GlobalOpt.cpp -o ..\GlobalOpt.obj
gpp @a -c src\lib\Tf\IPO\InferFunctionAttrs.cpp -o ..\InferFunctionAttrs.obj
gpp @a -c src\lib\Tf\IPO\InlineAlways.cpp -o ..\InlineAlways.obj
gpp @a -c src\lib\Tf\IPO\Inliner.cpp -o ..\Inliner.obj
gpp @a -c src\lib\Tf\IPO\InlineSimple.cpp -o ..\InlineSimple.obj
gpp @a -c src\lib\Tf\IPO\Internalize.cpp -o ..\Internalize.obj
gpp @a -c src\lib\Tf\IPO\IPConstantPropagation.cpp -o ..\IPConstantPropagation.obj
gpp @a -c src\lib\Tf\IPO\IPO.cpp -o ..\IPO.obj
gpp @a -c src\lib\Tf\IPO\LoopExtractor.cpp -o ..\LoopExtractor.obj
gpp @a -c src\lib\Tf\IPO\LowerBitSets.cpp -o ..\LowerBitSets.obj
gpp @a -c src\lib\Tf\IPO\MergeFunctions.cpp -o ..\MergeFunctions.obj
gpp @a -c src\lib\Tf\IPO\PartialInlining.cpp -o ..\PartialInlining.obj
gpp @a -c src\lib\Tf\IPO\PassManagerBuilder.cpp -o ..\PassManagerBuilder.obj
gpp @a -c src\lib\Tf\IPO\PruneEH.cpp -o ..\PruneEH.obj
gpp @a -c src\lib\Tf\IPO\SampleProfile.cpp -o ..\SampleProfile.obj
gpp @a -c src\lib\Tf\IPO\StripDeadPrototypes.cpp -o ..\StripDeadPrototypes.obj
gpp @a -c src\lib\Tf\IPO\StripSymbols.cpp -o ..\StripSymbols.obj
gpp @a -c src\lib\Tf\OC\DependencyAnalysis.cpp -o ..\DependencyAnalysis.obj
gpp @a -c src\lib\Tf\OC\ObjCARC.cpp -o ..\ObjCARC.obj
gpp @a -c src\lib\Tf\OC\ObjCARCAPElim.cpp -o ..\ObjCARCAPElim.obj
gpp @a -c src\lib\Tf\OC\ObjCARCContract.cpp -o ..\ObjCARCContract.obj
gpp @a -c src\lib\Tf\OC\ObjCARCExpand.cpp -o ..\ObjCARCExpand.obj
gpp @a -c src\lib\Tf\OC\ObjCARCOpts.cpp -o ..\ObjCARCOpts.obj
gpp @a -c src\lib\Tf\OC\ProvenanceAnalysis.cpp -o ..\ProvenanceAnalysis.obj
gpp @a -c src\lib\Tf\OC\ProvenanceAnalysisEvaluator.cpp -o ..\ProvenanceAnalysisEvaluator.obj
gpp @a -c src\lib\Tf\OC\PtrState.cpp -o ..\PtrState.obj
gpp @a -c src\lib\Tf\Scalar\ADCE.cpp -o ..\ADCE.obj
gpp @a -c src\lib\Tf\Scalar\AlignmentFromAssumptions.cpp -o ..\AlignmentFromAssumptions.obj
gpp @a -c src\lib\Tf\Scalar\BDCE.cpp -o ..\BDCE.obj
gpp @a -c src\lib\Tf\Scalar\ConstantHoisting.cpp -o ..\ConstantHoisting.obj
gpp @a -c src\lib\Tf\Scalar\ConstantProp.cpp -o ..\ConstantProp.obj
gpp @a -c src\lib\Tf\Scalar\CorrelatedValuePropagation.cpp -o ..\CorrelatedValuePropagation.obj
gpp @a -c src\lib\Tf\Scalar\DCE.cpp -o ..\DCE.obj
gpp @a -c src\lib\Tf\Scalar\DeadStoreElimination.cpp -o ..\DeadStoreElimination.obj
gpp @a -c src\lib\Tf\Scalar\EarlyCSE.cpp -o ..\EarlyCSE.obj
gpp @a -c src\lib\Tf\Scalar\FlattenCFGPass.cpp -o ..\FlattenCFGPass.obj
gpp @a -c src\lib\Tf\Scalar\Float2Int.cpp -o ..\Float2Int.obj
gpp @a -c src\lib\Tf\Scalar\GVN.cpp -o ..\GVN.obj
gpp @a -c src\lib\Tf\Scalar\InductiveRangeCheckElimination.cpp -o ..\InductiveRangeCheckElimination.obj
gpp @a -c src\lib\Tf\Scalar\IndVarSimplify.cpp -o ..\IndVarSimplify.obj
gpp @a -c src\lib\Tf\Scalar\JumpThreading.cpp -o ..\JumpThreading.obj
gpp @a -c src\lib\Tf\Scalar\LICM.cpp -o ..\LICM.obj
gpp @a -c src\lib\Tf\Scalar\LoadCombine.cpp -o ..\LoadCombine.obj
gpp @a -c src\lib\Tf\Scalar\LoopDeletion.cpp -o ..\LoopDeletion.obj
gpp @a -c src\lib\Tf\Scalar\LoopDistribute.cpp -o ..\LoopDistribute.obj
gpp @a -c src\lib\Tf\Scalar\LoopIdiomRecognize.cpp -o ..\LoopIdiomRecognize.obj
gpp @a -c src\lib\Tf\Scalar\LoopInstSimplify.cpp -o ..\LoopInstSimplify.obj
gpp @a -c src\lib\Tf\Scalar\LoopInterchange.cpp -o ..\LoopInterchange.obj
gpp @a -c src\lib\Tf\Scalar\LoopLoadElimination.cpp -o ..\LoopLoadElimination.obj
gpp @a -c src\lib\Tf\Scalar\LoopRerollPass.cpp -o ..\LoopRerollPass.obj
gpp @a -c src\lib\Tf\Scalar\LoopRotation.cpp -o ..\LoopRotation.obj
gpp @a -c src\lib\Tf\Scalar\LoopStrengthReduce.cpp -o ..\LoopStrengthReduce.obj
gpp @a -c src\lib\Tf\Scalar\LoopUnrollPass.cpp -o ..\LoopUnrollPass.obj
gpp @a -c src\lib\Tf\Scalar\LoopUnswitch.cpp -o ..\LoopUnswitch.obj
gpp @a -c src\lib\Tf\Scalar\LowerAtomic.cpp -o ..\LowerAtomic.obj
gpp @a -c src\lib\Tf\Scalar\LowerExpectIntrinsic.cpp -o ..\LowerExpectIntrinsic.obj
gpp @a -c src\lib\Tf\Scalar\MemCpyOptimizer.cpp -o ..\MemCpyOptimizer.obj
gpp @a -c src\lib\Tf\Scalar\MergedLoadStoreMotion.cpp -o ..\MergedLoadStoreMotion.obj
gpp @a -c src\lib\Tf\Scalar\NaryReassociate.cpp -o ..\NaryReassociate.obj
gpp @a -c src\lib\Tf\Scalar\PartiallyInlineLibCalls.cpp -o ..\PartiallyInlineLibCalls.obj
gpp @a -c src\lib\Tf\Scalar\PlaceSafepoints.cpp -o ..\PlaceSafepoints.obj
gpp @a -c src\lib\Tf\Scalar\Reassociate.cpp -o ..\Reassociate.obj
gpp @a -c src\lib\Tf\Scalar\Reg2Mem.cpp -o ..\Reg2Mem.obj
gpp @a -c src\lib\Tf\Scalar\RewriteStatepointsForGC.cpp -o ..\RewriteStatepointsForGC.obj
gpp @a -c src\lib\Tf\Scalar\Scalar.cpp -o ..\Scalar.obj
gpp @a -c src\lib\Tf\Scalar\Scalarizer.cpp -o ..\Scalarizer.obj
gpp @a -c src\lib\Tf\Scalar\ScalarReplAggregates.cpp -o ..\ScalarReplAggregates.obj
gpp @a -c src\lib\Tf\Scalar\SCCP.cpp -o ..\SCCP.obj
gpp @a -c src\lib\Tf\Scalar\SeparateConstOffsetFromGEP.cpp -o ..\SeparateConstOffsetFromGEP.obj
gpp @a -c src\lib\Tf\Scalar\SimplifyCFGPass.cpp -o ..\SimplifyCFGPass.obj
gpp @a -c src\lib\Tf\Scalar\Sink.cpp -o ..\Sink.obj
gpp @a -c src\lib\Tf\Scalar\SpeculativeExecution.cpp -o ..\SpeculativeExecution.obj
gpp @a -c src\lib\Tf\Scalar\SROA.cpp -o ..\SROA.obj
gpp @a -c src\lib\Tf\Scalar\StraightLineStrengthReduce.cpp -o ..\StraightLineStrengthReduce.obj
gpp @a -c src\lib\Tf\Scalar\StructurizeCFG.cpp -o ..\StructurizeCFG.obj
gpp @a -c src\lib\Tf\Scalar\TailRecursionElimination.cpp -o ..\TailRecursionElimination.obj
gpp @a -c src\lib\Tf\Utils\AddDiscriminators.cpp -o ..\AddDiscriminators.obj
gpp @a -c src\lib\Tf\Utils\ASanStackFrameLayout.cpp -o ..\ASanStackFrameLayout.obj
gpp @a -c src\lib\Tf\Utils\BasicBlockUtils.cpp -o ..\BasicBlockUtils.obj
gpp @a -c src\lib\Tf\Utils\BreakCriticalEdges.cpp -o ..\BreakCriticalEdges.obj
gpp @a -c src\lib\Tf\Utils\BuildLibCalls.cpp -o ..\BuildLibCalls.obj
gpp @a -c src\lib\Tf\Utils\BypassSlowDivision.cpp -o ..\BypassSlowDivision.obj
gpp @a -c src\lib\Tf\Utils\CloneFunction.cpp -o ..\CloneFunction.obj
gpp @a -c src\lib\Tf\Utils\CloneModule.cpp -o ..\CloneModule.obj
gpp @a -c src\lib\Tf\Utils\CmpInstAnalysis.cpp -o ..\CmpInstAnalysis.obj
gpp @a -c src\lib\Tf\Utils\CodeExtractor.cpp -o ..\CodeExtractor.obj
gpp @a -c src\lib\Tf\Utils\CtorUtils.cpp -o ..\CtorUtils.obj
gpp @a -c src\lib\Tf\Utils\DemoteRegToStack.cpp -o ..\DemoteRegToStack.obj
gpp @a -c src\lib\Tf\Utils\FlattenCFG.cpp -o ..\FlattenCFG.obj
gpp @a -c src\lib\Tf\Utils\GlobalStatus.cpp -o ..\GlobalStatus.obj
gpp @a -c src\lib\Tf\Utils\InlineFunction.cpp -o ..\InlineFunction.obj
gpp @a -c src\lib\Tf\Utils\InstructionNamer.cpp -o ..\InstructionNamer.obj
gpp @a -c src\lib\Tf\Utils\IntegerDivision.cpp -o ..\IntegerDivision.obj
gpp @a -c src\lib\Tf\Utils\LCSSA.cpp -o ..\LCSSA.obj
gpp @a -c src\lib\Tf\Utils\Local.cpp -o ..\Local.obj
gpp @a -c src\lib\Tf\Utils\LoopSimplify.cpp -o ..\LoopSimplify.obj
gpp @a -c src\lib\Tf\Utils\LoopUnroll.cpp -o ..\LoopUnroll.obj
gpp @a -c src\lib\Tf\Utils\LoopUnrollRuntime.cpp -o ..\LoopUnrollRuntime.obj
gpp @a -c src\lib\Tf\Utils\LoopUtils.cpp -o ..\LoopUtils.obj
gpp @a -c src\lib\Tf\Utils\LoopVersioning.cpp -o ..\LoopVersioning.obj
gpp @a -c src\lib\Tf\Utils\LowerInvoke.cpp -o ..\LowerInvoke.obj
gpp @a -c src\lib\Tf\Utils\LowerSwitch.cpp -o ..\LowerSwitch.obj
gpp @a -c src\lib\Tf\Utils\Mem2Reg.cpp -o ..\Mem2Reg.obj
gpp @a -c src\lib\Tf\Utils\MetaRenamer.cpp -o ..\MetaRenamer.obj
gpp @a -c src\lib\Tf\Utils\ModuleUtils.cpp -o ..\ModuleUtils.obj
gpp @a -c src\lib\Tf\Utils\PromoteMemoryToRegister.cpp -o ..\PromoteMemoryToRegister.obj
gpp @a -c src\lib\Tf\Utils\SimplifyCFG.cpp -o ..\SimplifyCFG.obj
gpp @a -c src\lib\Tf\Utils\SimplifyIndVar.cpp -o ..\SimplifyIndVar.obj
gpp @a -c src\lib\Tf\Utils\SimplifyInstructions.cpp -o ..\SimplifyInstructions.obj
gpp @a -c src\lib\Tf\Utils\SimplifyLibCalls.cpp -o ..\SimplifyLibCalls.obj
gpp @a -c src\lib\Tf\Utils\SplitModule.cpp -o ..\SplitModule.obj
gpp @a -c src\lib\Tf\Utils\SSAUpdater.cpp -o ..\SSAUpdater.obj
gpp @a -c src\lib\Tf\Utils\SymbolRewriter.cpp -o ..\SymbolRewriter.obj
gpp @a -c src\lib\Tf\Utils\UnifyFunctionExitNodes.cpp -o ..\UnifyFunctionExitNodes.obj
gpp @a -c src\lib\Tf\Utils\Utils.cpp -o ..\Utils.obj
gpp @a -c src\lib\Tf\Utils\ValueMapper.cpp -o ..\ValueMapper.obj
gpp @a -c src\lib\Tf\Vec\BBVectorize.cpp -o ..\BBVectorize.obj
gpp @a -c src\lib\Tf\Vec\LoopVectorize.cpp -o ..\LoopVectorize.obj
gpp @a -c src\lib\Tf\Vec\SLPVectorizer.cpp -o ..\SLPVectorizer.obj
gpp @a -c src\lib\Tf\Vec\Vectorize.cpp -o ..\Vectorize.obj
gpp @a -c src\lib\Tg\Target.cpp -o ..\Target.obj
gpp @a -c src\lib\Tg\TargetIntrinsicInfo.cpp -o ..\TargetIntrinsicInfo.obj
gpp @a -c src\lib\Tg\TargetLoweringObjectFile.cpp -o ..\TargetLoweringObjectFile.obj
gpp @a -c src\lib\Tg\TargetMachine.cpp -o ..\TargetMachine.obj
gpp @a -c src\lib\Tg\TargetMachineC.cpp -o ..\TargetMachineC.obj
gpp @a -c src\lib\Tg\TargetRecip.cpp -o ..\TargetRecip.obj
gpp @a -c src\lib\Tg\TargetSubtargetInfo.cpp -o ..\TargetSubtargetInfo.obj
gpp @a -c src\lib\Tg\X86\AsmParser\X86AsmInstrumentation.cpp -o ..\X86AsmInstrumentation.obj
gpp @a -c src\lib\Tg\X86\AsmParser\X86AsmParser.cpp -o ..\X86AsmParser.obj
gpp @a -c src\lib\Tg\X86\Disassembler\X86Disassembler.cpp -o ..\X86Disassembler.obj
gpp @a -c src\lib\Tg\X86\Disassembler\X86DisassemblerDecoder.cpp -o ..\X86DisassemblerDecoder.obj
gpp @a -c src\lib\Tg\X86\InstPrinter\X86ATTInstPrinter.cpp -o ..\X86ATTInstPrinter.obj
gpp @a -c src\lib\Tg\X86\InstPrinter\X86InstComments.cpp -o ..\X86InstComments.obj
gpp @a -c src\lib\Tg\X86\InstPrinter\X86IntelInstPrinter.cpp -o ..\X86IntelInstPrinter.obj
gpp @a -c src\lib\Tg\X86\MCTargetDesc\X86AsmBackend.cpp -o ..\X86AsmBackend.obj
gpp @a -c src\lib\Tg\X86\MCTargetDesc\X86ELFObjectWriter.cpp -o ..\X86ELFObjectWriter.obj
gpp @a -c src\lib\Tg\X86\MCTargetDesc\X86ELFRelocationInfo.cpp -o ..\X86ELFRelocationInfo.obj
gpp @a -c src\lib\Tg\X86\MCTargetDesc\X86MachObjectWriter.cpp -o ..\X86MachObjectWriter.obj
gpp @a -c src\lib\Tg\X86\MCTargetDesc\X86MachORelocationInfo.cpp -o ..\X86MachORelocationInfo.obj
gpp @a -c src\lib\Tg\X86\MCTargetDesc\X86MCAsmInfo.cpp -o ..\X86MCAsmInfo.obj
gpp @a -c src\lib\Tg\X86\MCTargetDesc\X86MCCodeEmitter.cpp -o ..\X86MCCodeEmitter.obj
gpp @a -c src\lib\Tg\X86\MCTargetDesc\X86MCTargetDesc.cpp -o ..\X86MCTargetDesc.obj
gpp @a -c src\lib\Tg\X86\MCTargetDesc\X86WinCOFFObjectWriter.cpp -o ..\X86WinCOFFObjectWriter.obj
gpp @a -c src\lib\Tg\X86\MCTargetDesc\X86WinCOFFStreamer.cpp -o ..\X86WinCOFFStreamer.obj
gpp @a -c src\lib\Tg\X86\TargetInfo\X86TargetInfo.cpp -o ..\X86TargetInfo.obj
gpp @a -c src\lib\Tg\X86\Utils\X86ShuffleDecode.cpp -o ..\X86ShuffleDecode.obj
gpp @a -c src\lib\Tg\X86\X86AsmPrinter.cpp -o ..\X86AsmPrinter.obj
gpp @a -c src\lib\Tg\X86\X86CallFrameOptimization.cpp -o ..\X86CallFrameOptimization.obj
gpp @a -c src\lib\Tg\X86\X86ExpandPseudo.cpp -o ..\X86ExpandPseudo.obj
gpp @a -c src\lib\Tg\X86\X86FastISel.cpp -o ..\X86FastISel.obj
gpp @a -c src\lib\Tg\X86\X86FixupLEAs.cpp -o ..\X86FixupLEAs.obj
gpp @a -c src\lib\Tg\X86\X86FloatingPoint.cpp -o ..\X86FloatingPoint.obj
gpp @a -c src\lib\Tg\X86\X86FrameLowering.cpp -o ..\X86FrameLowering.obj
gpp @a -c src\lib\Tg\X86\X86InstrInfo.cpp -o ..\X86InstrInfo.obj
gpp @a -c src\lib\Tg\X86\X86ISelDAGToDAG.cpp -o ..\X86ISelDAGToDAG.obj
gpp @a -c src\lib\Tg\X86\X86ISelLowering.cpp -o ..\X86ISelLowering.obj
gpp @a -c src\lib\Tg\X86\X86MachineFunctionInfo.cpp -o ..\X86MachineFunctionInfo.obj
gpp @a -c src\lib\Tg\X86\X86MCInstLower.cpp -o ..\X86MCInstLower.obj
gpp @a -c src\lib\Tg\X86\X86OptimizeLEAs.cpp -o ..\X86OptimizeLEAs.obj
gpp @a -c src\lib\Tg\X86\X86PadShortFunction.cpp -o ..\X86PadShortFunction.obj
gpp @a -c src\lib\Tg\X86\X86RegisterInfo.cpp -o ..\X86RegisterInfo.obj
gpp @a -c src\lib\Tg\X86\X86SelectionDAGInfo.cpp -o ..\X86SelectionDAGInfo.obj
gpp @a -c src\lib\Tg\X86\X86ShuffleDecodeConstantPool.cpp -o ..\X86ShuffleDecodeConstantPool.obj
gpp @a -c src\lib\Tg\X86\X86Subtarget.cpp -o ..\X86Subtarget.obj
gpp @a -c src\lib\Tg\X86\X86TargetMachine.cpp -o ..\X86TargetMachine.obj
gpp @a -c src\lib\Tg\X86\X86TargetObjectFile.cpp -o ..\X86TargetObjectFile.obj
gpp @a -c src\lib\Tg\X86\X86TargetTransformInfo.cpp -o ..\X86TargetTransformInfo.obj
gpp @a -c src\lib\Tg\X86\X86VZeroUpper.cpp -o ..\X86VZeroUpper.obj
gpp @a -c src\lib\Tg\X86\X86WinEHState.cpp -o ..\X86WinEHState.obj
pause
